site_name: ARPES Python tools
repo_url: https://pranabdas.github.io/
site_description: Documentation for ARPES Python Tools by Pranab Das.
site_author: Pranab Das

nav:
    - Table of Contents: index.md
    - Getting Started: gs.md
    - Importing Data: data-import.md
    - Image Plot: image-plot.md
    - k-space Conversion: k-conv.md
    - Extracting Line Profile: line-profile.md
    - Slicing plane: plane-slice.md
    - Rotate map data: rotate.md
    - Crop Image (2D data): crop.md
    - Import/Export Igor text: igor-text.md

theme:
    name: null
    custom_dir: simplicity
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true
    hljs_languages: [python]

markdown_extensions:
    - pymdownx.arithmatex
    - attr_list

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML
