site_name: ARPES Python tools
site_url: https://pranabdas.github.io/
repo_url: https://github.com/pranabdas/
repo_name: homepage 
site_description: Documentation for ARPES Python Tools by Pranab Das.
site_author: Pranab Das 

nav:
    - Home: index.md
    - Getting Started: gs.md
    - Importing Data : data-import.md
    - Image Plot : image-plot.md
    - k-space Conversion : k-conv.md
    - Extracting Line Profile : line-profile.md
    - Slicing plane : plane-slice.md
    - Rotate map data : rotate.md
    - Crop Image (2D data): crop.md
    - Import/Export Igor text : igor-text.md
    - About: about.md 

theme: 
    name: null 
    custom_dir: myreadthedocs 
    static_templates:
        - 404.html

    include_search_page: true
    search_index_only: false

    highlightjs: true
    hljs_languages: python

copyright: © Copyright 2020 <a href="https://pranabdas.github.io">Pranab Das</a>. All rights reserved.  

# google_analytics: [UA-163317742-1, https://pranabdas.github.io/]
