name = "arpespythontools"
pages_build_output_dir = "./build"

[pages]
build_command = """
    sed -i 's|baseUrl:.*|baseUrl: "/",|I' docusaurus.config.js
    npm run build
    """

[vars]
NODE_VERSION = "lts/*"
